//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Banking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Check_174797_Project
    {
        [Required(ErrorMessage = "Please Enter Check ID")]
        public long Check_ID { get; set; }
        [Required(ErrorMessage = "Please provide your Account number")]
        public Nullable<long> Account_no { get; set; }
        [Required(ErrorMessage = "Please Enter Phone number")]
        public Nullable<long> phoneno { get; set; }
        [Required(ErrorMessage = "Please Enter Address")]
        public string address { get; set; }
    
        public virtual Account_Master_174797_Project Account_Master_174797_Project { get; set; }
    }
}
