//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Banking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Loan_174797_Project
    {
        [Required(ErrorMessage = "Please Enter Loan ID")]
        public long LoanID { get; set; }
        [Required(ErrorMessage = "Please Enter Account Id")]
        public Nullable<long> AccountID { get; set; }
        [Required(ErrorMessage = "Please select your loan type")]
        public string TypeofLoan { get; set; }
        [Required(ErrorMessage = "Please Enter Amount of loan")]
        public Nullable<long> Loanammount { get; set; }
        [Required(ErrorMessage = "Please Enter Loan duration")]
        public Nullable<double> DurationofLoan { get; set; }

        public Nullable<double> EMI { get; set; }
        public string Applicationstatus { get; set; }
        [Required(ErrorMessage = "Please Enter Your Email ID")]
        public string Email { get; set; }
    
        public virtual Account_Master_174797_Project Account_Master_174797_Project { get; set; }
    }
}
