//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Banking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Training_20Feb_MumbaiEntities2 : DbContext
    {
        public Training_20Feb_MumbaiEntities2()
            : base("name=Training_20Feb_MumbaiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Master_174797_Project> Account_Master_174797_Project { get; set; }
        public virtual DbSet<Loan_174797_Project> Loan_174797_Project { get; set; }
        public virtual DbSet<Transactions_174797_Project> Transactions_174797_Project { get; set; }
        public virtual DbSet<BillPay> BillPays { get; set; }
        public virtual DbSet<Payee> Payees { get; set; }
        public virtual DbSet<Check_174797_Project> Check_174797_Project { get; set; }
    }
}
