//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Banking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transactions_174797_Project
    {
        
        public long Transaction_ID { get; set; }
        [Display(Name = "DateofTransaction")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateofTransaction { get; set; }
        [Required(ErrorMessage = "Please Enter Transaction Type")]
        public string TypeofTransaction { get; set; }
        [Required(ErrorMessage = "Please Enter Account number")]
        public Nullable<long> Account_No { get; set; }
        [Required(ErrorMessage = "Please Enter Amount")]
        public Nullable<int> Amount { get; set; }
    
        public virtual Account_Master_174797_Project Account_Master_174797_Project { get; set; }
    }
}
